# -*- coding: utf-8 -*-
"""Kevin Icaza colab2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FF4W05C_U-SpCx2D4ecGVCQ3FgDoxurm
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

#tabla de datos seleccionada muestra B y C
data = {
    'Muestra B': [14, 9, 4, 12, 15],
    'Muestra C': [1, 5, 4, 3, 6]
}

#crear dataframe
df = pd.DataFrame(data)
print(df)

#Tabla de datos
print(df.describe())

#analisis de las muestras B y C
X1=(1, 5, 4, 3, 6)
Y1=(14, 9, 4, 12, 15)

#COLOR
# Define x-axis positions for the bars
x_pos = np.arange(len(X1))

plt.bar(x_pos, X1, label="barra amarillo", color="yellow")
plt.plot(x_pos, Y1, label="barra verde", color="red", linestyle='-') # Use a standard linestyle like '-'

plt.xlabel('Muestra C')
plt.ylabel('Muestra B')
plt.legend()
plt.show()

"""EN EL ANALISIS DE VARIANZA QUE HICIMOS DESCUBRIMOS UN SOLO MARGEN DE ERROR EN LA BARRA 2 DE LAS MUESTRAS B Y C"""